import { IMAGES } from "@/constant";

export const ALL_STUDENTS = [
  {
    rank: 1,
    name: "Ahan Kumar",
    class: "Class 8",
    points: 830,
    accuracy: "96",
    streak: "15 day streak",
    lessons: 68,
    profileImg: IMAGES.user,
    badge: "trophy-gold",
  },
  {
    rank: 2,
    name: "Hvff",
    class: "Class 7",
    points: 295,
    accuracy: "94",
    streak: "12 day streak",
    lessons: 45,
    profileImg: IMAGES.user,
    badge: "trophy-silver",
  },
  {
    rank: 3,
    name: "Flower Girl",
    class: "Class 6",
    points: 190,
    accuracy: "93",
    streak: "8 day streak",
    lessons: 38,
    profileImg: IMAGES.user,
    badge: "trophy-bronze",
  },
  {
    rank: 4,
    name: "12 June Child Test",
    class: "Class 5",
    points: 165,
    accuracy: "92",
    streak: "6 day streak",
    lessons: 32,
    profileImg: IMAGES.user,
  },
  {
    rank: 5,
    name: "Hcdff",
    class: "Class 4",
    points: 160,
    accuracy: "91",
    streak: "5 day streak",
    lessons: 30,
    profileImg: IMAGES.user,
  },
  {
    rank: 6,
    name: "Eva",
    class: "Class 3",
    points: 145,
    accuracy: "90",
    streak: "4 day streak",
    lessons: 28,
    profileImg: IMAGES.user,
  },
  {
    rank: 7,
    name: "Sophia Kim",
    class: "Class 2",
    points: 138,
    accuracy: "89",
    streak: "7 day streak",
    lessons: 26,
    profileImg: IMAGES.user,
  },
  {
    rank: 8,
    name: "James Wilson",
    class: "Class 6",
    points: 132,
    accuracy: "88",
    streak: "3 day streak",
    lessons: 23,
    profileImg: IMAGES.user,
  },
  {
    rank: 9,
    name: "Olivia Davis",
    class: "Class 5",
    points: 128,
    accuracy: "87",
    streak: "9 day streak",
    lessons: 22,
    profileImg: IMAGES.user,
  },
  {
    rank: 10,
    name: "Liam Garcia",
    class: "Class 1",
    points: 120,
    accuracy: "86",
    streak: "2 day streak",
    lessons: 20,
    profileImg: IMAGES.user,
  },
  {
    rank: 11,
    name: "Ava Marti",
    class: "Class 3",
    points: 4100,
    accuracy: "85",
    streak: "2 day streak",
    lessons: 20,
    profileImg: IMAGES.user,
  },
  {
    rank: 12,
    name: "Noah Thomas",
    class: "Class 4",
    points: 3950,
    accuracy: "83",
    streak: "2 day streak",
    lessons: 20,
    profileImg: IMAGES.user,
  },
]